version: "3"

services:
  redis:
    profiles:
      - no-battery
      - no-coordinator
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - mvp-network

  influxdb:
    profiles:
      - no-battery
      - no-coordinator
    image: influxdb:1.8-alpine
    container_name: influxdb
    platform: linux/x86_64
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - mvp-network

  grafana:
    profiles:
      - no-battery
      - no-coordinator
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - mvp-network

  zookeeper:
    profiles:
      - no-battery
      - no-coordinator
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    depends_on:
      - redis
    networks:
      - mvp-network

  kafka:
    profiles:
      - no-battery
      - no-coordinator
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - mvp-network

  tso:
    profiles:
      - no-battery
      - no-coordinator
    build: ./tso
    platform: linux/x86_64
    depends_on:
      - kafka
    environment:
      - BROKER=kafka
      - BROKER_URL=kafka
      - BROKER_PORT=9092
    networks:
      - mvp-network

  battery:
    profiles:
      - no-coordinator
    build: ./battery-sim
    platform: linux/x86_64
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - kafka
    environment:
      - BROKER_URL=kafka:9092
      - BROKER=KAFKA
      - N_BATTERIES=2
    networks:
      - mvp-network

volumes:
  influxdb_data:
  grafana:


networks:
  mvp-network:
